name: "Install gRPC Dependencies"
description: "Install gRPC dependencies"
inputs: {}
outputs: {}
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      id: install-dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libprotobuf-dev libprotoc-dev protobuf-compiler autoconf libtool
    - name: Install grpc-java
      shell: bash
      id: install-grpc-java
      run: |
        mkdir -p $HOME/protobuf
        curl -L https://github.com/protocolbuffers/protobuf/archive/${PROTOBUF_VERSION}.tar.gz | tar xvz --strip-components=1 -C $HOME/protobuf
        cd $HOME/protobuf
        autoreconf -f -i -Wall,no-obsolete
        ./configure --prefix=/usr --enable-static=no
        make -j2
        sudo make install
        mkdir -p $HOME/grpc-java
        curl -L https://github.com/grpc/grpc-java/archive/${GRPC_JAVA_VERSION}.tar.gz | tar xvz --strip-components=1 -C $HOME/grpc-java
        cd $HOME/grpc-java/compiler/src/java_plugin/cpp
        g++ -I. -I$HOME/protobuf/src \
        *.cpp \
        -L$HOME/protobuf/src/.libs \
        -lprotoc -lprotobuf -lpthread --std=c++0x -s \
        -o protoc-gen-grpc-java
        cp protoc-gen-grpc-java $HOME/grpc-java
      env:
        PROTOBUF_VERSION: v3.17.3
        GRPC_JAVA_VERSION: v1.40.0
