// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vald/apis/proto/v1/discoverer/discoverer.proto

package org.vdaas.vald.api.v1.discoverer;

public final class ValdDiscoverer {
  private ValdDiscoverer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n.vald/apis/proto/v1/discoverer/discover" +
      "er.proto\022\rdiscoverer.v1\032#apis/proto/v1/p" +
      "ayload/payload.proto\032=github.com/googlea" +
      "pis/googleapis/google/api/annotations.pr" +
      "oto2\303\001\n\nDiscoverer\022X\n\004Pods\022\036.payload.v1." +
      "Discoverer.Request\032\025.payload.v1.Info.Pod" +
      "s\"\031\202\323\344\223\002\023\"\016/discover/pods:\001*\022[\n\005Nodes\022\036." +
      "payload.v1.Discoverer.Request\032\026.payload." +
      "v1.Info.Nodes\"\032\202\323\344\223\002\024\"\017/discover/nodes:\001" +
      "*Bc\n org.vdaas.vald.api.v1.discovererB\016V" +
      "aldDiscovererP\001Z-github.com/vdaas/vald/a" +
      "pis/grpc/v1/discovererb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.vdaas.vald.api.v1.payload.ValdPayload.getDescriptor(),
          com.google.api.AnnotationsProto.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    org.vdaas.vald.api.v1.payload.ValdPayload.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
