// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vald/apis/proto/v1/manager/index/index_manager.proto

package org.vdaas.vald.api.v1.manager.index;

public final class ValdIndexManager {
  private ValdIndexManager() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n4vald/apis/proto/v1/manager/index/index" +
      "_manager.proto\022\020manager.index.v1\032#apis/p" +
      "roto/v1/payload/payload.proto\032=github.co" +
      "m/googleapis/googleapis/google/api/annot" +
      "ations.proto2Z\n\005Index\022Q\n\tIndexInfo\022\021.pay" +
      "load.v1.Empty\032\034.payload.v1.Info.Index.Co" +
      "unt\"\023\202\323\344\223\002\r\022\013/index/infoBk\n#org.vdaas.va" +
      "ld.api.v1.manager.indexB\020ValdIndexManage" +
      "rP\001Z0github.com/vdaas/vald/apis/grpc/v1/" +
      "manager/indexb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.vdaas.vald.api.v1.payload.ValdPayload.getDescriptor(),
          com.google.api.AnnotationsProto.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    org.vdaas.vald.api.v1.payload.ValdPayload.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
