name: build protobuf
on:
  repository_dispatch:

jobs:
  build:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Install gRPC dependencies
        uses: ./.github/actions/install-grpc-dependencies
      - uses: actions/checkout@v1
        with:
          fetch-depth: 10
      - name: checkout master
        run: |
          git checkout master
      - name: build
        run: |
          export GOPATH=$HOME/go
          export PATH=$HOME/grpc-java:$PATH
          make all
          make vald/sha/update
          make vald/client/java/version/update
          rm -rf vald
      - name: commit and push
        run: |
          sha=`make vald/sha/print`
          git config --global user.name 'VDaaS org'
          git config --global user.email 'ci@vdaas.org'
          git remote set-url origin https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
          git add .
          git commit -m "Update [vald sha: ${sha}]"
          git push
        env:
          GITHUB_USER: ${{ secrets.CI_USER }}
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
      - name: tag
        continue-on-error: true
        run: |
          version=`make vald/client/java/version/print`
          git tag ${version}
          git push --tags
